server:
  port: 8381

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: p1

server:
  port: 8381

---
spring:
  profiles: p2

server:
  port: 8382

---
spring:
  profiles: p3

server:
  port: 8383
